# .zshrc — the shared shell core lives in ~/.config/zsh/common.zsh.
# Keep this file to the prompt and desktop-session extras.
source ~/.config/zsh/common.zsh

# ── Two-line prompt ─────────────────────────────────────────────
autoload -Uz colors && colors

# prompt colors come from ~/.config/zsh/theme.zsh (GENERATED by theme-set:
# dragon/redlight); the :-defaults below are the dragon palette, so a missing
# file (e.g. before the first theme-set run) still yields the classic look
[[ -r ~/.config/zsh/theme.zsh ]] && source ~/.config/zsh/theme.zsh

configure_prompt() {
    PROMPT="%F{${THEME_FRAME:-#8a9a7b}}┌──%F{${THEME_PAREN:-#7aa89f}}(%B%F{${THEME_GLYPH:-#957fb8}} %b%F{${THEME_PAREN:-#7aa89f}})%F{${THEME_FRAME:-#8a9a7b}}-%F{${THEME_PAREN:-#7aa89f}}[%B%F{${THEME_PATH:-#7fb4ca}} %(6~.%-1~/…/%4~.%5~)%b%F{${THEME_PAREN:-#7aa89f}}]"$'\n'"%F{${THEME_FRAME:-#8a9a7b}}└─%B%F{${THEME_ARROW:-#c34043}}%b%F{reset} "
}
configure_prompt

# follow theme-set in EXISTING shells too: before each prompt, if the mode
# file changed, re-read theme.zsh and rebuild the prompt. One stat per prompt
# — negligible — and a no-op when nothing changed.
_theme_mode_file="${XDG_STATE_HOME:-$HOME/.local/state}/theme/mode"
precmd_theme_check() {
  local m
  m="$(stat -c %Y "$_theme_mode_file" 2>/dev/null || echo 0)"
  if [[ "$m" != "${_theme_mtime:-}" ]]; then
    _theme_mtime="$m"
    [[ -r ~/.config/zsh/theme.zsh ]] && source ~/.config/zsh/theme.zsh
    configure_prompt
  fi
}
autoload -Uz add-zsh-hook
add-zsh-hook precmd precmd_theme_check

# admin tools live in /usr/sbin; Debian doesn't add it for non-login shells
export PATH="$PATH:/usr/sbin:/sbin"

# host-local extras (machine-specific PATH entries, private aliases)
[[ -r ~/.zshrc.local ]] && source ~/.zshrc.local

# ssh-agent: persistent per-user agent (systemd unit ssh-agent.service).
# With AddKeysToAgent in ~/.ssh/config the key passphrase is entered once
# per boot, not once per terminal.
export SSH_AUTH_SOCK="${XDG_RUNTIME_DIR:-/run/user/$UID}/ssh-agent.socket"

# Attach to (or create) the default tmux session on every new terminal
if [[ -z "$TMUX" ]]; then
    tmux new-session -A -s default
fi
